In [38]:
import numpy as np
import pandas as pd

In [39]:
df = pd.read_csv('data.csv')

In [40]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [41]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [46]:
str_index = list(df.dtypes[df.dtypes == 'str'].index)
str_index

['make',
 'model',
 'engine_fuel_type',
 'transmission_type',
 'driven_wheels',
 'market_category',
 'vehicle_size',
 'vehicle_style']

In [43]:
for col in str_index:
    df[col] = col.lower().replace(' ','_')

In [44]:
df.head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,make,model,2011,engine_fuel_type,335.0,6.0,transmission_type,driven_wheels,2.0,market_category,vehicle_size,vehicle_style,26,19,3916,46135
1,make,model,2011,engine_fuel_type,300.0,6.0,transmission_type,driven_wheels,2.0,market_category,vehicle_size,vehicle_style,28,19,3916,40650
2,make,model,2011,engine_fuel_type,300.0,6.0,transmission_type,driven_wheels,2.0,market_category,vehicle_size,vehicle_style,28,20,3916,36350
3,make,model,2011,engine_fuel_type,230.0,6.0,transmission_type,driven_wheels,2.0,market_category,vehicle_size,vehicle_style,28,18,3916,29450
4,make,model,2011,engine_fuel_type,230.0,6.0,transmission_type,driven_wheels,2.0,market_category,vehicle_size,vehicle_style,28,18,3916,34500